language: node_js
node_js:
- '8'
notifications:
  email: false
deploy:
  provider: npm
  email: davidstoreypickart@gmail.com
  api_key:
    secure: Vh92AAGXgf+DwiF7XmyvFhUmRyc/xgg7DUrn/ECGljJZm59GIBp1dUGASvmDargMQrkM1ZXjvi/vc/ynTupI6cicuRKgfax3xhyw1Z3pQ2uFlZOitgtwoyQTJHt1lCm4wupM+JsFWxJ+vmNrc0p/t5HqLR2zYMu7ReYrKdmb5263DehgQnNZkU/Udd9kVot4ck0PGcaFb/sDxc2u7r93DzQQMi67Yvm9or/9s8o0zg0psi1Bkqex4v0OlKA5z29RjrFJVpepQLrcYiledlshiLsHK16Cm94GPoWVj+qo+K3V3vmYR2lqA3EuFdREcOgUYFw6TZboFKTISFCk8i4cTIphoNYY915tnw9TIb/Ft054W9ZM5QpDQBav7f6eiOfuc83G0HeFGZb2aPLV1BCZF7R0grTQTKk7pLuUW1xJNbe2Ln1g4x7o1EX0WRWp4j5ooAb073a/UZBpay7HbIruu5yXEkQWPqaL4L6FzuV8seH8okrBd3QvecCtNowpjIXZFG1UQOv0fOUHL+1t0ZL0MtNtqG/TKg69rDB2h5EIxBj5xYb/nfqTefligVcuTgjePrsOqgKinmmHtHIMmgcLdBbFghACHB+L5IO+G4Wmz19t74LV4OqeZoRUM//gW7anZy1O20r3Qo6nHwwv3l1TmjjwXLrP/vXYt6IinaQ91Hc=
  on:
    branch: master
  skip_cleanup: true
